config/routes.rb
Rails.application.routes.draw do
  resources :exams do
    member do
      get 'exam_version'
      get 'evaluate_answer'
      get 'generate_version'
      post 'scan_answer'
      get 'select_questions'
      get 'show_pdf_file'
      get 'update_master'
      get 'update_json_master'
    end
  end
  resources :signatures do
    member do
      get 'search'
    end
  end


  resources :teachers
  resources :options
  resources :questions
  resources :roles

  devise_for :users

  get 'home/index'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: 'home#index'
end

app/models/signature.rb
class Signature < ApplicationRecord
  has_many :questions
  has_many :users, through: :teachers
end

app/controllers/signatures_controller.rb
class SignaturesController < ApplicationController
  before_action :check_user_log_in
  before_action :set_signature, only: [:show, :edit, :update, :destroy, :search]

  # GET /signatures
  # GET /signatures.json
  def index
    @signatures = Signature.all
  end

  # GET /signatures/1
  # GET /signatures/1.json
  def show
  end

  def search
    text = params[:searched_text]
    @results = {}

    # Searching Labels
      @results['labels'] = nil
      @results['labels'] = [text] if not @signature.labels.remove(' ').split(',').find_index(text).nil?
    # Searching Exams
    # Searching Questions
  end

  # GET /signatures/new
  def new
    @signature = Signature.new
  end

  # GET /signatures/1/edit
  def edit
  end

  # POST /signatures
  # POST /signatures.json
  def create
    @signature = Signature.new(signature_params)

    respond_to do |format|
      if @signature.save
        format.html { redirect_to @signature, notice: 'Signature was successfully created.' }
        format.json { render :show, status: :created, location: @signature }
      else
        format.html { render :new }
        format.json { render json: @signature.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /signatures/1
  # PATCH/PUT /signatures/1.json
  def update
    respond_to do |format|
      if @signature.update(signature_params)
        format.html { redirect_to @signature, notice: 'Signature was successfully updated.' }
        format.json { render :show, status: :ok, location: @signature }
      else
        format.html { render :edit }
        format.json { render json: @signature.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /signatures/1
  # DELETE /signatures/1.json
  def destroy
    @signature.destroy
    respond_to do |format|
      format.html { redirect_to signatures_url, notice: 'Signature was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_signature
      @signature = Signature.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def signature_params
      signature_params = params.require(:signature).permit(:name, :labels)

      if not signature_params[:labels].nil?
        signature_params[:labels] = signature_params[:labels].remove(' ').split(',').sort.join(", ")
      end
      signature_params
    end

    def check_user_log_in
    if not user_signed_in?
      redirect_to(user_session_path)
    end
  end
end

app/helpers/signatures_helper.rb
module SignaturesHelper
end

app/views/signatures/_form.html.erb
<head>

</head>
<body>
    <%= form_for(signature) do |f| %>
    <% if signature.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(signature.errors.count, "error") %> prohibited this signature from being saved:</h2>

        <ul>
        <% signature.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
        </ul>
      </div>
    <% end %>

    <br/>

    <div class="form form-group">
      <%= f.label :name %>
      <%= f.text_field :name, class: "form form-control" %>
    </div>

    <div class="form form-group">
      <%= f.label :labels %>
      <%= f.text_area :labels, class: "form form-control" %>
    </div>

    <input class="btn btn-primary" name="commit" value="Submit" data-disable-with="Submit" type="submit">
<% end %>
</body>

app/views/signatures/_question_options.erb
<body>

  <p>Options for: "<%= @question.body %>"</p>

  <%= link_to "+ New Option", {:controller => "options", :action => "new", :question_id => @question.id}, class: "btn btn-primary" %>

  <table class="table table-responsive">
    <thead>
    <tr>
      <th>Body</th>
      <th>True or false</th>
      <th colspan="3"></th>
    </tr>
    </thead>

    <tbody>
    <% @options = Option.where(:question_id => @question.id) %>
    <% @options.each do |option| %>
        <tr>
          <td><%= option.body %></td>
          <td><%= if option.true_or_false == 1; "True" else "False" end %></td>
          <td><%= link_to 'Show', option %></td>
          <td><%= link_to 'Edit', edit_option_path(option) %></td>
          <td><%= link_to 'Destroy', option, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        </tr>
    <% end %>
    </tbody>
  </table>

</body>

app/views/signatures/edit.html.erb
<h1>Editing Labels</h1>
<h4>Signature: <%= @signature.name %></h4>

<%= form_for(@signature) do |f| %>
    <% if @signature.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(@signature.errors.count, "error") %> prohibited this signature from being saved:</h2>

          <ul>
            <% @signature.errors.full_messages.each do |message| %>
                <li><%= message %></li>
            <% end %>
          </ul>
        </div>
    <% end %>

    <br/>

    <div class="form form-group">
      <% if User.find(current_user.id).role_id == 1 %>
          <%= f.label :name %>
          <%= f.text_area :name, class: "form form-control" %>
      <% else %>
          <%= f.hidden_field :name %>
      <% end %>
    </div>

    <div class="form form-group">
      <%= f.label :labels %>
      <%= f.text_area :labels, class: "form form-control" %>
    </div>

    <input class="btn btn-primary" name="commit" value="Update Signature" data-disable-with="Update Signature" type="submit">

    <%= link_to 'Back', signature_path(@signature.id), class: "btn btn-primary" %>

<% end %>

app/views/signatures/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Signatures</h1>

<%= link_to '+ New Signature', new_signature_path, class: "btn btn-primary" %>

<br/>

<table class="table table-striped">
  <thead>
    <tr>
      <th>Name</th>
      <th>Labels</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @signatures.each do |signature| %>
      <tr>
        <td><%= signature.name %></td>
        <td><%= signature.labels %></td>
        <td><%= link_to 'Show', signature %></td>
        <td><%= link_to 'Edit', edit_signature_path(signature) %></td>
        <td><%= link_to 'Destroy', signature, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

app/views/signatures/new.html.erb
<h1>New Signature</h1>

<%= render 'form', signature: @signature %>

app/views/signatures/search.html.erb
<h1> <%= @signature.name %></h1>

<form class="navbar-form navbar-left" action="<%= url_for(:controller => 'signatures', :action => 'search') %>" accept-charset="UTF-8" method="get">
  <div class="form form-group">
    <input class="form-control" type="text" name="searched_text" id="searched_text" placeholder="Search">
  </div>

  <input class="btn btn-default" name="commit" value="Search" data-disable-with="Submit" type="submit">
</form>

<br/>
<br/>
<br/>

<% text = params[:searched_text] %>
<h4>Search Results for "<%= text %>" ...</h4>

<h3>Labels</h3>
  <% if @results['labels'].nil?%>
    <p>Not results found.</p>
  <% else %>
    <p><%= @results['labels'][0] %></p>
  <% end %>

<h3>Exams</h3>
  <% exams = Exam.where("signature_id = ? AND (title LIKE ? OR header LIKE ? OR labels LIKE ? OR description LIKE ?)", @signature.id, "%#{text}%", "%#{text}%", "%#{text}%", "%#{text}%").paginate(:page => params[:exam_page], :per_page => 10) %>
  <br/><%= will_paginate exams, :param_name => 'exam_page' %>
  <table class="table table-striped">
    <thead>
    <tr>
      <th>Title</th>
      <th>Header</th>
      <th>Description</th>
      <th>Labels</th>
      <th>Amount</th>
      <th colspan="3"></th>
    </tr>
    </thead>
    <tbody>
      <% exams.each do |exam| %>
        <tr>
          <td><%= exam.title %></td>
          <td><%= exam.header %></td>
          <td><%= exam.description %></td>
          <td><%= exam.labels %></td>
          <td><%= exam.amount %></td>
          <td><%= link_to 'Show', exam %></td>
          <td><%= link_to 'Edit', edit_exam_path(exam) %></td>
          <td><%= link_to 'Destroy', exam, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        </tr>
      <% end %>
    </tbody>
  </table>

<h3>Questions</h3>
  <% questions = Question.where("signature_id = ? AND (title LIKE ? OR body LIKE ? OR labels LIKE ?)", @signature.id, "%#{text}%", "%#{text}%", "%#{text}%").paginate(:page => params[:question_page], :per_page => 10) %>
  <br/><%= will_paginate questions, :param_name => 'question_page' %>
  <table class="table table-striped">
    <thead>
    <tr>
      <th></th>
      <th>Title</th>
      <th>Body</th>
      <th>Labels</th>
      <th>Signature</th>
      <th colspan="3"></th>
    </tr>
    </thead>

    <tbody>
    <% count = 0 %>
    <% questions.each do |question| %>
        <tr>
          <td><a data-toggle="tab" aria-controls="q<%= count %>" href="#q<%= count %>"><span class="glyphicon glyphicon-list"></span>Options</a></td>
          <td><%= question.title %></td>
          <td><%= question.body %></td>
          <td><%= question.labels %></td>
          <td><%= question.signature.name %></td>
          <td><%= link_to 'Show', question %></td>
          <td><%= link_to 'Edit', edit_question_path(question) %></td>
          <td><%= link_to 'Destroy', question, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        </tr>
        <% count += 1 %>
    <% end %>
    </tbody>
  </table>

  <div class="tab-content">
    <% count = 0 %>
    <% questions.each do |question| %>
        <div class="tab-pane" id="q<%= count %>">
          <table class="col-md-6">
            <p>Options for: "<%= question.body %>"</p>

            <table class="table table-responsive">
              <thead>
              <tr>
                <th>Body</th>
                <th>True or false</th>
                <th colspan="3"></th>
              </tr>
              </thead>

              <tbody>
              <% options = Option.where(:question_id => question.id) %>
              <% options.each do |option| %>
                  <tr>
                    <td><%= option.body %></td>
                    <td><%= option.true_or_false %></td>
                    <td><%= link_to 'Show', option %></td>
                    <td><%= link_to 'Edit', edit_option_path(option) %></td>
                    <td><%= link_to 'Destroy', option, method: :delete, data: { confirm: 'Are you sure?' } %></td>
                  </tr>
              <% end %>
              </tbody>
            </table>
          </table>
        </div>
        <% count += 1 %>
    <% end %>
  </div>

app/views/signatures/show.html.erb
<h1> <%= @signature.name %></h1>

<form class="navbar-form navbar-left" action="<%= url_for(:controller => 'signatures', :action => 'search') %>" accept-charset="UTF-8" method="get">
  <div class="form form-group">
    <input class="form-control" type="text" name="searched_text" id="searched_text" placeholder="Search">
  </div>

  <input class="btn btn-default" name="commit" value="Search" data-disable-with="Submit" type="submit">
</form>

<br/>
<br/>

<h3> Labels <a href="<%= edit_signature_path(@signature.id) %>"><span class="glyphicon glyphicon-pencil"></span>edit</a></h3>
<p> <%= @signature.labels %> </p>

<h3> Exams </h3>

<%= link_to "+ New Exam", {:controller => "exams", :action => "new", :signature_id => @signature.id }, :class => "btn btn-primary" %>

<% exams = Exam.where(:signature_id => @signature.id).paginate(:page => params[:exam_page], :per_page => 5) %>
<br/><%= will_paginate exams, :param_name => 'exam_page' %>
<table class="table table-striped">
  <thead>
  <tr>
    <th>Title</th>
    <th>Header</th>
    <th>Description</th>
    <th>Labels</th>
    <th>Amount</th>
    <th colspan="3"></th>
  </tr>
  </thead>

  <tbody>
  <% exams.each do |exam| %>
      <tr>
        <td><%= exam.title %></td>
        <td><%= exam.header %></td>
        <td><%= exam.description %></td>
        <td><%= exam.labels %></td>
        <td><%= exam.amount %></td>
        <td><%= link_to 'Show', exam %></td>
        <td><%= link_to 'Edit', edit_exam_path(exam) %></td>
        <td><%= link_to 'Destroy', exam, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
  <% end %>
  </tbody>
</table>

<h3> Questions </h3>

<%= link_to "+ New Question", {:controller => "questions", :action => "new", :signature_id => @signature.id }, :class => "btn btn-primary" %>

<% questions = Question.where(:signature_id => @signature.id).paginate(:page => params[:question_page], :per_page => 5) %>
<br/><%= will_paginate questions, :param_name => 'question_page' %>
<table class="table table-striped">
  <thead>
  <tr>
    <th></th>
    <th>Title</th>
    <th>Body</th>
    <th>Labels</th>
    <th>Signature</th>
    <th colspan="3"></th>
  </tr>
  </thead>

  <tbody>
  <% count = 0 %>
  <% questions.each do |question| %>
      <tr>
        <td><a data-toggle="tab" aria-controls="q<%= count %>" href="#q<%= count %>"><span class="glyphicon glyphicon-list"></span>Options</a></td>
        <td><%= question.title %></td>
        <td><%= question.body %></td>
        <td><%= question.labels %></td>
        <td><%= question.signature.name %></td>
        <td><%= link_to 'Show', question %></td>
        <td><%= link_to 'Edit', edit_question_path(question) %></td>
        <td><%= link_to 'Destroy', question, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
      <% count += 1 %>
  <% end %>
  </tbody>
</table>

<div class="tab-content">
  <% count = 0 %>
  <% questions.each do |question| %>
      <div class="tab-pane" id="q<%= count %>">
        <div class="col-md-6">
          <% @question = question %>
          <%= render partial: 'question_options' %>
        </div>
      </div>
      <% count += 1 %>
  <% end %>
</div>